#!/usr/bin/env bash
# Bash script configuring an Ubuntu server with the requirements provided
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
